#
# -*- coding:utf-8 -*-
#
# Autogenerated by Thrift Compiler (1.0.0)
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#
#  options string: py:coding=utf-8,new_style,utf8strings
#

from thrift.Thrift import TType, TMessageType, TException, TApplicationException
from ttypes import *

NC_GET_DATA_SOURCE = "msg://commonsvc/datasource"
NC_COMMIT_JOB = "msg://commonsvc/commitjob"
NC_STOP_JOB = "msg://commonsvc/stopjob"
NC_CHECK_PROCESS_EXISTS = "msg://commonsvc/checkprocess"
NC_DB_INSTANCE_VERIFY = "msg://commonsvc/db_instance_verify"
NC_CLIENT_INFO_VERIFY = "msg://commonsvc/nc_client_info_verify"
NC_CHECK_PATH_EX = "msg://commonsvc/detect_path"
NC_CLIENT_DB_USERS = "msg://commonsvc/client_dbusers"
