# -*- coding: UTF-8 -*-
#
# Autogenerated by Thrift Compiler (0.13.0)
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#
#  options string: py:coding=UTF-8
#

from thrift.Thrift import TType, TMessageType, TFrozenDict, TException, TApplicationException
from thrift.protocol.TProtocol import TProtocolException
from thrift.TRecursive import fix_spec

import sys
from .ttypes import *
NC_CKCLIENT_REGISTER_NODE = "msg://ckclient/client/registernode"
NC_CKCLIENT_GET_NODE_LIST = "msg://ckclient/client/getnodelist"
NC_CKCLIENT_REGISTER_NODE_LIST = "msg://ckclient/client/registernodelist"
