#
# -*- coding:utf-8 -*-
#
# Autogenerated by Thrift Compiler (1.0.0)
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#
#  options string: py:coding=utf-8,new_style,utf8strings
#

from thrift.Thrift import TType, TMessageType, TException, TApplicationException
from ttypes import *

NC_GET_DATA_SOURCE_LIST = "msg://datasource/server/getdatasource"
NC_SCAN_CLIENT = "msg://datasource/server/scanclient"
NC_VERIFY_CONFIG_INFO = "msg://datasource/server/verifyconfig"
NC_GET_OS_USER_LIST = "msg://datasource/server/getosuserlist"
NC_CHECK_PATH = "msg://datasource/server/checkpath"
NC_CAN_SUPPORT_APP = "msg://datasource/server/getapplicaton"
