# -*- coding: UTF-8 -*-
#
# Autogenerated by Thrift Compiler (0.13.0)
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#
#  options string: py:coding=UTF-8
#

from thrift.Thrift import TType, TMessageType, TFrozenDict, TException, TApplicationException
from thrift.protocol.TProtocol import TProtocolException
from thrift.TRecursive import fix_spec

import sys
from .ttypes import *
CUR_VERSION = 20200526
BAK_TYPE = "bak_type"
XID = "xid"
TIME = "time"
INS_NAME = "ins_name"
INS_DSN = "ins_dsn"
USERNAME = "username"
PASSWORD = "password"
DATA_FULLPATH = "data_path"
WAL_FULLPATH = "wal_path"
DATA_BACKUPPATH = "data_backuppath"
WAL_BACKUPPATH = "wal_backuppath"
LATEST_LOGNAME = "latest_logname"
DATABASE_VERSION = "database_version"
