#
# -*- coding:utf-8 -*-
#
# Autogenerated by Thrift Compiler (1.0.0)
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#
#  options string: py:coding=utf-8,new_style,utf8strings
#

from thrift.Thrift import TType, TMessageType, TException, TApplicationException
import ncException.ttypes
import ncBaseHeader.ttypes
import ncCommonType_Var.ttypes
import ncEEFJobBase.ttypes
import ncDataSource.ttypes
import ncClient.ttypes
import ncCloudStorage.ttypes
import ncForEPMS.ttypes
import ncScheTask_Var.ttypes
import ncScheTask.ttypes
import ncDBInstance.ttypes
import ncServer.ttypes
import ncStrategy.ttypes
import ncPlatform.ttypes
import ncProjectUser.ttypes
import ncVirtualSafety.ttypes
import ncUser.ttypes
import ncAmsJob.ttypes
import ncJob.ttypes
import ncEcssCommonDefinition.ttypes


from thrift.transport import TTransport
from thrift.protocol import TBinaryProtocol, TProtocol
try:
  from thrift.protocol import fastbinary
except:
  fastbinary = None


